name: Java User API - CI

on: 
  push:
    branches:
      - main
    paths:
      - 'apis/user-java/**' 
  pull_request:
    branches:
      - main
    paths:
      - 'apis/user-java/**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: apis/user-java
        run: mvn --batch-mode --update-snapshots verify